//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./service_types');
//HELPER FUNCTIONS AND STRUCTURES

var TestService_doTest_args = function(args) {
  this.id = null;
  this.str = null;
  if (args) {
    if (args.id !== undefined) {
      this.id = args.id;
    }
    if (args.str !== undefined) {
      this.str = args.str;
    }
  }
};
TestService_doTest_args.prototype = {};
TestService_doTest_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.id = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.str = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TestService_doTest_args.prototype.write = function(output) {
  output.writeStructBegin('TestService_doTest_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.I32, 1);
    output.writeI32(this.id);
    output.writeFieldEnd();
  }
  if (this.str !== null && this.str !== undefined) {
    output.writeFieldBegin('str', Thrift.Type.STRING, 2);
    output.writeString(this.str);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TestService_doTest_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
TestService_doTest_result.prototype = {};
TestService_doTest_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.I32) {
        this.success = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TestService_doTest_result.prototype.write = function(output) {
  output.writeStructBegin('TestService_doTest_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.I32, 0);
    output.writeI32(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TestServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
TestServiceClient.prototype = {};
TestServiceClient.prototype.seqid = function() { return this._seqid; }
TestServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
TestServiceClient.prototype.doTest = function(id, str, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_doTest(id, str);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_doTest(id, str);
  }
};

TestServiceClient.prototype.send_doTest = function(id, str) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('doTest', Thrift.MessageType.CALL, this.seqid());
  var args = new TestService_doTest_args();
  args.id = id;
  args.str = str;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

TestServiceClient.prototype.recv_doTest = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new TestService_doTest_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('doTest failed: unknown result');
};
var TestServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
TestServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

TestServiceProcessor.prototype.process_doTest = function(seqid, input, output) {
  var args = new TestService_doTest_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.doTest.length === 2) {
    Q.fcall(this._handler.doTest, args.id, args.str)
      .then(function(result) {
        var result = new TestService_doTest_result({success: result});
        output.writeMessageBegin("doTest", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new TestService_doTest_result(err);
        output.writeMessageBegin("doTest", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.doTest(args.id, args.str,  function (err, result) {
      var result = new TestService_doTest_result((err != null ? err : {success: result}));
      output.writeMessageBegin("doTest", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

